export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';

export const PUT_SUPERADMINS_PENDING = 'PUT_SUPERADMINS_PENDING';
export const PUT_SUPERADMINS_ERROR = 'PUT_SUPERADMINS_ERROR';
export const PUT_SUPERADMINS_SUCCESS = 'PUT_SUPERADMINS_SUCCESS';

export const DEL_SUPERADMINS_PENDING = 'DEL_SUPERADMINS_PENDING';
export const DEL_SUPERADMINS_ERROR = 'DEL_SUPERADMINS_ERROR';
export const DEL_SUPERADMINS_SUCCESS = 'DEL_SUPERADMINS_SUCCESS';

export const ADD_SUPERADMINS_PENDING = 'ADD_SUPERADMINS_PENDING';
export const ADD_SUPERADMINS_ERROR = 'ADD_SUPERADMINS_ERROR';
export const ADD_SUPERADMINS_SUCCESS = 'ADD_SUPERADMINS_SUCCESS';

export const GET_BY_ID_SUPERADMINS_PENDING = 'GET_BY_ID_SUPERADMINS_PENDING';
export const GET_BY_ID_SUPERADMINS_ERROR = 'GET_BY_ID_SUPERADMINS_ERROR';
export const GET_BY_ID_SUPERADMINS_SUCCESS = 'GET_BY_ID_SUPERADMINS_SUCCESS';
