export const GET_CLASSES_PENDING = 'GET_CLASSES_PENDING';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const DELETE_CLASSES_PENDING = 'DELETE_CLASSES_PENDING';
export const DELETE_CLASSES_SUCCESS = 'DELETE_CLASSES_SUCCESS';
export const DELETE_CLASSES_ERROR = 'DELETE_CLASSES_ERROR';
