export const GET_CLASSES_PENDING = 'GET_CLASSES_PENDING';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const DEL_CLASSES_PENDING = 'DELETE_CLASSES_PENDING';
export const DEL_CLASSES_SUCCESS = 'DELETE_CLASSES_SUCCESS';
export const DEL_CLASSES_ERROR = 'DELETE_CLASSES_ERROR';

export const ADD_CLASSES_PENDING = 'DELETE_CLASSES_PENDING';
export const ADD_CLASSES_SUCCESS = 'DELETE_CLASSES_SUCCESS';
export const ADD_CLASSES_ERROR = 'DELETE_CLASSES_ERROR';

export const PUT_CLASSES_PENDING = 'PUT_CLASSES_PENDING';
export const PUT_CLASSES_SUCCESS = 'PUT_CLASSES_SUCCESS';
export const PUT_CLASSES_ERROR = 'PUT_CLASSES_ERROR';

export const GET_BY_ID_CLASSES_PENDING = 'GET_BY_ID_CLASSES_PENDING';
export const GET_BY_ID_CLASSES_SUCCESS = 'GET_BY_ID_CLASSES_SUCCESS';
export const GET_BY_ID_CLASSES_ERROR = 'GET_BY_ID_CLASSES_ERROR';
