export const GET_CLASSES_PENDING = 'GET_CLASSES_PENDING';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const DELETE_CLASS_PENDING = 'DELETE_CLASSES_PENDING';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASSES_SUCCESS';
export const DELETE_CLASS_ERROR = 'DELETE_CLASSES_ERROR';

export const POST_CLASS_PENDING = 'DELETE_CLASSES_PENDING';
export const POST_CLASS_SUCCESS = 'DELETE_CLASSES_SUCCESS';
export const POST_CLASS_ERROR = 'DELETE_CLASSES_ERROR';

export const PUT_CLASS_PENDING = 'PUT_CLASSES_PENDING';
export const PUT_CLASS_SUCCESS = 'PUT_CLASSES_SUCCESS';
export const PUT_CLASS_ERROR = 'PUT_CLASSES_ERROR';

export const GET_BY_ID_CLASS_PENDING = 'GET_BY_ID_CLASS_PENDING';
export const GET_BY_ID_CLASS_SUCCESS = 'GET_BY_ID_CLASS_SUCCESS';
export const GET_BY_ID_CLASS_ERROR = 'GET_BY_ID_CLASS_ERROR';
