export const GET_ACTIVITIES_PENDING = 'GET_ACTIVITIES_PENDING';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';

export const PUT_ACTIVITY_PENDING = 'PUT_ACTIVITY_PENDING';
export const PUT_ACTIVITY_ERROR = 'PUT_ACTIVITY_ERROR';
export const PUT_ACTIVITY_SUCCESS = 'PUT_ACTIVITY_SUCCESS';

export const DEL_ACTIVITY_PENDING = 'DEL_ACTIVITY_PENDING';
export const DEL_ACTIVITY_ERROR = 'DEL_ACTIVITY_ERROR';
export const DEL_ACTIVITY_SUCCESS = 'DEL_ACTIVITY_SUCCESS';

export const ADD_ACTIVITY_PENDING = 'ADD_ACTIVITY_PENDING';
export const ADD_ACTIVITY_ERROR = 'ADD_ACTIVITY_ERROR';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';

export const GET_BY_ID_ACITIVITY_PENDING = 'GET_BY_ID_ACITIVITY_PENDING';
export const GET_BY_ID_ACITIVITY_ERROR = 'GET_BY_ID_ACITIVITY_ERROR';
export const GET_BY_ID_ACITIVITY_SUCCESS = 'GET_BY_ID_ACITIVITY_SUCCESS';
