export const GET_ACTIVITIES_PENDING = 'GET_ACTIVITIES_PENDING';
export const GET_ACTIVITIES_ERROR = 'GET_ACTIVITIES_ERROR';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';

export const PUT_ACTIVITY_PENDING = 'PUT_ACTIVITY_PENDING';
export const PUT_ACTIVITY_ERROR = 'PUT_ACTIVITY_ERROR';
export const PUT_ACTIVITY_SUCCESS = 'PUT_ACTIVITY_SUCCESS';

export const DELETE_ACTIVITY_PENDING = 'DELETE_ACTIVITY_PENDING';
export const DELETE_ACTIVITY_ERROR = 'DELETE_ACTIVITY_ERROR';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';

export const POST_ACTIVITY_PENDING = 'POST_ACTIVITY_PENDING';
export const POST_ACTIVITY_ERROR = 'POST_ACTIVITY_ERROR';
export const POST_ACTIVITY_SUCCESS = 'POST_ACTIVITY_SUCCESS';
